### ISSUE TITLE
update biocommons hgvs to newer version

### ISSUE THREAD

**Issue by kantale** [kantale/MutationInfo#21]
```
INFO:root:Connecting to biocommons uta..
DEBUG:hgvs.dataproviders.uta:connecting to postgresql://anonymous:anonymous@uta.biocommons.org/uta/uta_20150827...
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    mi = MutationInfo()
  File "/Users/alexandroskanterakis/anaconda2/envs/MutationInfoEnv/lib/python2.7/site-packages/MutationInfo-1.3.0-py2.7.egg/MutationInfo/__init__.py", line 253, in __init__
    self.biocommons_connect()
  File "/Users/alexandroskanterakis/anaconda2/envs/MutationInfoEnv/lib/python2.7/site-packages/MutationInfo-1.3.0-py2.7.egg/MutationInfo/__init__.py", line 302, in biocommons_connect
    self.biocommons_hdp = hgvs_biocommons_uta.connect()
  File "/Users/alexandroskanterakis/anaconda2/envs/MutationInfoEnv/lib/python2.7/site-packages/hgvs-0.4.13-py2.7.egg/hgvs/dataproviders/uta.py", line 75, in connect
  File "/Users/alexandroskanterakis/anaconda2/envs/MutationInfoEnv/lib/python2.7/site-packages/hgvs-0.4.13-py2.7.egg/hgvs/dataproviders/uta.py", line 504, in __init__
  File "/Users/alexandroskanterakis/anaconda2/envs/MutationInfoEnv/lib/python2.7/site-packages/hgvs-0.4.13-py2.7.egg/hgvs/dataproviders/uta.py", line 163, in __init__
  File "/Users/alexandroskanterakis/anaconda2/envs/MutationInfoEnv/lib/python2.7/site-packages/hgvs-0.4.13-py2.7.egg/hgvs/dataproviders/uta.py", line 519, in _connect
  File "/Users/alexandroskanterakis/anaconda2/envs/MutationInfoEnv/lib/python2.7/site-packages/psycopg2-2.7-py2.7-macosx-10.7-x86_64.egg/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: invalid port number: "None"

```

**Comment by kantale** [comment]
Solved in 454dd6e
