### ISSUE TITLE
Library not loaded: libssl.1.0.0.dylib

### ISSUE THREAD

**Issue by kantale** [kantale/MutationInfo#5]
```
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/psycopg2-2.6.2-py2.7-macosx-10.6-x86_64.egg/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/psycopg2-2.6.2-py2.7-macosx-10.6-x86_64.egg/psycopg2/_psycopg.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/psycopg2-2.6.2-py2.7-macosx-10.6-x86_64.egg/psycopg2/_psycopg.so
  Reason: image not found
```

**Comment by kantale** [comment]
This happens when importing:
```python
import hgvs.dataproviders.uta as hgvs_biocommons_uta 
```

**Comment by kantale** [comment]
Added appropriate message on setup.py and on main script during library import 	2dd7b02
