### ISSUE TITLE
shelve module needs bsddn, bsddb3 or gdm 

### ISSUE THREAD

**Issue by kantale** [kantale/MutationInfo#6]
```
>>> from MutationInfo import MutatioInfo as MI
>>> mi = MI()
I need an email to query Entrez. Please insert one: alexandros.kanterakis@gmail.com
Downloading: http://hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/chromFa.tar.gz Bytes: 948736151
Progress[************100%**********************]  948731905 of 948736151 complete
Downloading: https://github.com/counsyl/hgvs/raw/master/pyhgvs/data/genes.refGene Bytes: 12449349
Progress[************100%**********************]  12443649 of 12449349 complete
WARNING dbfile.open_index: Falling back to hash index: unable to import bsddb
WARNING:pygr-log:Falling back to hash index: unable to import bsddb
DEBUG seqdb._create_seqLenDict: Building sequence length index...
DEBUG:pygr-log:Building sequence length index...
WARNING dbfile.open_index: Falling back to hash index: unable to import bsddb
WARNING:pygr-log:Falling back to hash index: unable to import bsddb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/MutationInfo-0.0.1-py2.7.egg/MutationInfo/__init__.py", line 200, in __init__
    genome = self.genome,
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/MutationInfo-0.0.1-py2.7.egg/MutationInfo/__init__.py", line 1919, in __init__
    self.sequence_genome = SequenceFileDB(self.fasta_filename)
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/pygr-0.8.2-py2.7-macosx-10.6-x86_64.egg/pygr/seqdb.py", line 433, in __init__
    SequenceDB.__init__(self, filepath=filepath, dbname=dbname, **kwargs)
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/pygr-0.8.2-py2.7-macosx-10.6-x86_64.egg/pygr/seqdb.py", line 232, in __init__
    self._set_seqtype()
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/pygr-0.8.2-py2.7-macosx-10.6-x86_64.egg/pygr/seqdb.py", line 244, in _set_seqtype
    for seqID in self: # get an iterator
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/pygr-0.8.2-py2.7-macosx-10.6-x86_64.egg/pygr/seqdb.py", line 304, in __iter__
    return iter(self.seqInfoDict)
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/pygr-0.8.2-py2.7-macosx-10.6-x86_64.egg/pygr/seqdb.py", line 517, in __iter__
    return iter(self.seqDB.seqLenDict)
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/pygr-0.8.2-py2.7-macosx-10.6-x86_64.egg/pygr/dbfile.py", line 150, in __iter__
    Original error message was: %s''' % str(exc_value))
TypeError: cannot iterate over this dictionary.
This means that you do not have bsddb, bsddb3, or gdbm available for use by
the 'shelve' module in this Python install.  Please fix this!

Original error message was: 'dbm.dbm' object is not iterable

```

**Comment by kantale** [comment]
Steps in OSX 10.11.5:
* brew install berkeley-db 
* Download and untar  bsddb3 from here: https://pypi.python.org/pypi/bsddb3/6.2.1 
* Install with: ```python setup.py --berkeley-db-incdir=/usr/local/Cellar/berkeley-db/6.1.19/include/ --berkeley-db-libdir=/usr/local/Cellar/berkeley-db/6.1.19/lib/ install```
