### ISSUE TITLE
ImportError: No module named MySQLdb

### ISSUE THREAD

**Issue by kantale** [kantale/MutationInfo#7]
```
>>> from MutationInfo import MutationInfo as MI
>>> a = MI()
I need an email to query Entrez. Please insert one: alexandros.kanterakis@gmail.com
DEBUG seqdb._create_seqLenDict: Building sequence length index...
DEBUG:pygr-log:Building sequence length index...
WARNING:root:Could not determine file size
Downloading: http://databases.lovd.nl/shared/api/rest.php/genes Bytes: None

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/MutationInfo-0.0.1-py2.7.egg/MutationInfo/__init__.py", line 226, in __init__
    self.ucsc = UCSC_genome(self.genome)
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/cruzdb-0.5.6-py2.7.egg/cruzdb/__init__.py", line 63, in __init__
    soup.Genome.__init__(self, self.dburl)
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/cruzdb-0.5.6-py2.7.egg/cruzdb/sqlsoup.py", line 209, in __init__
    self._metadata = MetaData(engine_or_metadata)
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3389, in __init__
    self.bind = bind
  File "<string>", line 1, in <lambda>
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3485, in _bind_to
    self._bind = sqlalchemy.create_engine(bind)
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/Users/alexandroskanterakis/anaconda2/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 92, in dbapi
    return __import__('MySQLdb')
ImportError: No module named MySQLdb
```

**Comment by kantale** [comment]
Resolved on OSX 10.11.5 with:
* ```brew install mysql```
* ```pip install mysql-python```
